language: node_js

sudo: required

node_js:
  - "8"

branches:
  only:
    - master

install:
  - npm install

before_script:
  - npm run lint:md
  - npm run lint:text
  
script:
  - true
 
notifications:
   on_success: change
   on_failure: always
