site_name: Academy
site_url: https://fiware-academy.readthedocs.org
repo_url: https://github.com/fiware/academy
site_description: Fiware Academy
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
google_analytics: ["UA-83719923-1", 'fiware-academy.readthedocs.io']
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_neutral.css"]
pages:
  - Home: 'index.md'
  - 'Integrated Courses':
    - 'FIWARE Webinars': 'integrated-courses/webinars.md'
    - 'CEF Smart Cities': 'integrated-courses/cef-smart-cities.md'
    - 'FIWARE for Smart Cities': 'integrated-courses/smart-cities.md'
  - 'Core Context Managment':
    - 'Cygnus': 'core/cygnus.md'
    - 'Draco': 'core/draco.md'
    - 'Orion': 'core/orion.md'
    - 'Orion-LD': 'core/orion-ld.md'
    - 'QuantumLeap': 'core/quantum-leap.md'
    - 'Scorpio': 'core/scorpio.md'
    - 'STH-Comet': 'core/sth-comet.md'
  - 'IoT Agents, Robots & Third Party Systems': 
    - 'Domibus': 'third-party/domibus.md'
    - 'Fast-RTPS': 'robotics/fast-rtps.md'
    - 'IoT Agents': 'iot-agents/idas.md'
    - 'Open MTC': 'iot-agents/open-mtc.md'
  - 'Security':
    - 'Authzforce': 'security/authzforce.md'
    - 'Keyrock': 'security/keyrock.md'
    - 'Wilma': 'security/wilma.md'
  - 'Processing, Analysis and Visualization':
    - 'Cosmos': 'processing/cosmos.md'
    - 'FogFlow': 'processing/fogflow.md'
    - 'Knowage': 'processing/knowage.md'
    - 'Kurento': 'processing/kurento.md'
    - 'Wirecloud': 'processing/wirecloud.md'
  - 'Data Publication':
    - 'Biz Ecosystem': 'data-publication/business-api.md'
    - 'CKAN': 'data-publication/ckan.md'
    - 'APInf': 'data-publication/apinf.md'
